Purnomo-Ribut/managamenrestoran

app/Http/Controllers/manager/KategoriController.php
app/Kategori.php
app/tbl_kategoris.php
app/tbl_menus.php
database/migrations/2023_11_28_024540_create_tbl_kategoris_table.php
database/migrations/2023_11_28_024809_create_tbl_menuses_table.php
resources/views/manager/manager.blade.php
resources/views/manager/test.blade.php
routes/web.php

masih mmrlukan proses lanjutan

migrate kategori dan menu

---

public/assets/kasir/css/style.css
resources/views/kasir/dashboard.blade.php

Kasir dashboard

---

app/Http/Controllers/manager/KategoriController.php
app/Kategori.php
resources/views/manager/manager.blade.php
routes/web.php

bantu perbaiki redirect nya ya bang

berhasil insert data, tapi redirect ketika berhasil masih eror

---

app/Http/Controllers/Kasir/CheckoutController.php
resources/views/kasir/checkout.blade.php
routes/web.php

add checkout page

---

app/Http/Controllers/manager/MenuController.php
app/Menu.php
database/migrations/2023_11_28_024809_create_tbl_menuses_table.php
resources/views/manager/manager.blade.php
routes/web.php

upload gambar berhasil dan storage sudah ngelink

---

app/Http/Controllers/LoginController.php
app/Http/Kernel.php
app/Http/Middleware/Authenticate.php
app/Http/Middleware/CheckRole.php
database/migrations/2014_10_12_000000_create_users_table.php
database/seeds/DatabaseSeeder.php
database/seeds/UserSeeder.php
resources/views/login/index.blade.php
routes/web.php

Fitur: multiple user login

---

app/Http/Controllers/manager/KategoriController.php
app/Http/Controllers/manager/MenuController.php
app/Menu.php
resources/views/manager/lihat_kategori.blade.php
resources/views/manager/lihat_menu.blade.php
resources/views/manager/manager.blade.php
routes/web.php

acc bang, sayangnya setealah lihat data, upload gambar menjadi gagal

membuat tampilan tampil data kategori & menu

---

app/Http/Controllers/manager/DashboardManController.php
app/Http/Controllers/manager/KategoriController.php
routes/web.php

perbaiki route pada manager

---

app/Http/Controllers/manager/MenuController.php
resources/views/manager/lihat_menu.blade.php
routes/web.php

edit menu berhasil, tinggal penyempurnaan

---

app/Http/Controllers/Chef/DashboardController.php
resources/views/chef/dashboard.blade.php
resources/views/chef/master/navbar.blade.php
resources/views/chef/master/sidebar.blade.php
resources/views/chef/master/template.blade.php
resources/views/chef/test.blade.php
routes/web.php

Update Dashboard Chef

---

app/Http/Controllers/manager/KategoriController.php
app/Http/Controllers/manager/MenuController.php
database/migrations/2023_11_28_024809_create_tbl_menuses_table.php
public/assets/manager/css/style.css
resources/views/manager/lihat_kategori.blade.php
resources/views/manager/lihat_menu.blade.php
resources/views/manager/manager.blade.php
resources/views/manager/master/template.blade.php
routes/web.php

tinggal improve ke sweet alert dan data tabel, tentunya perlu bantuan untuk desain dashboard

hapus menu dan kategori berhasil, 

---

app/Chef.php
app/Http/Controllers/manager/ChefController.php
database/migrations/2023_12_08_041223_create_chefs_table.php
resources/views/login/index.blade.php
resources/views/manager/chef.blade.php
resources/views/manager/manager.blade.php
routes/web.php

CRUD Chef Berhasil

---

resources/views/manager/chef.blade.php
resources/views/manager/lihat_menu.blade.php
resources/views/manager/manager.blade.php
resources/views/manager/master/chef/template.blade.php
resources/views/manager/master/karyawan/template.blade.php
resources/views/manager/master/kategori/template.blade.php
resources/views/manager/master/menu/template.blade.php
resources/views/manager/master/sidebar.blade.php
resources/views/manager/master/template.blade.php

update side bar dan dashboard manager monitoring data

---

database/migrations/2023_12_05_134750_create_tbl_orders.php

ganti users menjadi tbl_users

---

app/Http/Controllers/LoginController.php
resources/views/manager/lihat_menu.blade.php
resources/views/manager/manager.blade.php
resources/views/manager/master/template.blade.php

acc ngabbb.. untuk konfirmasi aus belum selssai

pasang alert selepas login

---

app/Http/Controllers/Chef/DashboardController.php
app/Http/Controllers/Chef/ProfileController.php
app/Http/Controllers/LoginController.php
resources/views/chef/dashboard.blade.php
resources/views/chef/master/sidebar.blade.php
routes/web.php

membanu dasar foreach kak alma

---

app/Http/Controllers/manager/DashboardManController.php
database/seeds/UserSeeder.php
public/assets/manager/css/style.css
resources/views/chef/master/sidebar.blade.php
resources/views/kasir/checkout.blade.php
resources/views/manager/manager.blade.php
resources/views/manager/master/sidebar.blade.php
resources/views/manager/master/template.blade.php
routes/web.php

monitoring data pelanggan & monitoring pemasukan solve

---

resources/views/manager/manager.blade.php

data tabel pada dashboard manager

data tabel manager 1

---

resources/views/manager/lihat_menu.blade.php
resources/views/manager/manager.blade.php

dataaa tabel menuu bang purrrr

dt tbl menu

---

app/Http/Controllers/manager/MenuController.php
app/Http/Controllers/manager/ProfilController.php
app/Menu.php
database/migrations/2023_11_28_024809_create_tbl_menuses_table.php
resources/views/kasir/master/navbar.blade.php
resources/views/kasir/master/profil/template.blade.php
resources/views/kasir/master/sidebar.blade.php
resources/views/kasir/profil/index.blade.php
resources/views/manager/lihat_menu.blade.php
resources/views/manager/master/profil/template.blade.php
resources/views/manager/master/sidebar.blade.php
resources/views/manager/profil.blade.php

modifikasi profil pada kasir dan manager, dan menghilangkan stock

---

resources/views/kasir/dashboard.blade.php

update search di order list & transaction list

---

resources/views/chef/dashboard.blade.php
resources/views/chef/master/sidebar.blade.php

ubah tampilan list order jadi data table

ubah tampilan jadi data table

---

app/Http/Controllers/Customer/OrderController.php
resources/views/Customer/Menu.blade.php
resources/views/Customer/cekout.blade.php
resources/views/Customer/modal.blade.php
resources/views/Customer/reservation.blade.php
routes/web.php

cancel order from customer
